#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="prabhatdatabase")]
public partial class pDataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertadmin(admin instance);
  partial void Updateadmin(admin instance);
  partial void Deleteadmin(admin instance);
  partial void Insertalumini_info(alumini_info instance);
  partial void Updatealumini_info(alumini_info instance);
  partial void Deletealumini_info(alumini_info instance);
  #endregion
	
	public pDataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["prabhatdatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public pDataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pDataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public pDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<admin> admins
	{
		get
		{
			return this.GetTable<admin>();
		}
	}
	
	public System.Data.Linq.Table<alumini_info> alumini_infos
	{
		get
		{
			return this.GetTable<alumini_info>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _username;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public admin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(20) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumini_info")]
public partial class alumini_info : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Enrolment_No;
	
	private string _Full_name;
	
	private string _Passing_Year;
	
	private string _Branch;
	
	private string _status;
	
	private string _Email;
	
	private string _contact_no;
	
	private string _Address;
	
	private string _image_name;
	
	private string _image_path;
	
	private string _password;
	
	private string _mother_name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEnrolment_NoChanging(string value);
    partial void OnEnrolment_NoChanged();
    partial void OnFull_nameChanging(string value);
    partial void OnFull_nameChanged();
    partial void OnPassing_YearChanging(string value);
    partial void OnPassing_YearChanged();
    partial void OnBranchChanging(string value);
    partial void OnBranchChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void Oncontact_noChanging(string value);
    partial void Oncontact_noChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void Onimage_nameChanging(string value);
    partial void Onimage_nameChanged();
    partial void Onimage_pathChanging(string value);
    partial void Onimage_pathChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onmother_nameChanging(string value);
    partial void Onmother_nameChanged();
    #endregion
	
	public alumini_info()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enrolment_No", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Enrolment_No
	{
		get
		{
			return this._Enrolment_No;
		}
		set
		{
			if ((this._Enrolment_No != value))
			{
				this.OnEnrolment_NoChanging(value);
				this.SendPropertyChanging();
				this._Enrolment_No = value;
				this.SendPropertyChanged("Enrolment_No");
				this.OnEnrolment_NoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Full_name
	{
		get
		{
			return this._Full_name;
		}
		set
		{
			if ((this._Full_name != value))
			{
				this.OnFull_nameChanging(value);
				this.SendPropertyChanging();
				this._Full_name = value;
				this.SendPropertyChanged("Full_name");
				this.OnFull_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passing_Year", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
	public string Passing_Year
	{
		get
		{
			return this._Passing_Year;
		}
		set
		{
			if ((this._Passing_Year != value))
			{
				this.OnPassing_YearChanging(value);
				this.SendPropertyChanging();
				this._Passing_Year = value;
				this.SendPropertyChanged("Passing_Year");
				this.OnPassing_YearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Branch
	{
		get
		{
			return this._Branch;
		}
		set
		{
			if ((this._Branch != value))
			{
				this.OnBranchChanging(value);
				this.SendPropertyChanging();
				this._Branch = value;
				this.SendPropertyChanged("Branch");
				this.OnBranchChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(MAX)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="VarChar(13)")]
	public string contact_no
	{
		get
		{
			return this._contact_no;
		}
		set
		{
			if ((this._contact_no != value))
			{
				this.Oncontact_noChanging(value);
				this.SendPropertyChanging();
				this._contact_no = value;
				this.SendPropertyChanged("contact_no");
				this.Oncontact_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_name", DbType="VarChar(50)")]
	public string image_name
	{
		get
		{
			return this._image_name;
		}
		set
		{
			if ((this._image_name != value))
			{
				this.Onimage_nameChanging(value);
				this.SendPropertyChanging();
				this._image_name = value;
				this.SendPropertyChanged("image_name");
				this.Onimage_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_path", DbType="VarChar(50)")]
	public string image_path
	{
		get
		{
			return this._image_path;
		}
		set
		{
			if ((this._image_path != value))
			{
				this.Onimage_pathChanging(value);
				this.SendPropertyChanging();
				this._image_path = value;
				this.SendPropertyChanged("image_path");
				this.Onimage_pathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(20)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mother_name", DbType="VarChar(15)")]
	public string mother_name
	{
		get
		{
			return this._mother_name;
		}
		set
		{
			if ((this._mother_name != value))
			{
				this.Onmother_nameChanging(value);
				this.SendPropertyChanging();
				this._mother_name = value;
				this.SendPropertyChanged("mother_name");
				this.Onmother_nameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
